apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-team
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: This project is for the devops team
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: devops-team
    server: https://kubernetes.default.svc