apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-team-dev
  namespace: argocd
  labels:
    service: applications
spec:
  project: devops-team
  source:
    repoURL: https://github.com/vidal777/backstage-kubernetes-deployments
    targetRevision: HEAD
    path: ./deployments/devops-team/dev/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-team
  syncPolicy:
    automated:
      prune: true
      selfHeal: true